# Generated by Django 4.2.7 on 2023-11-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Cataory',
            new_name='Sub_Catagory',
        ),
    ]
