# Generated by Django 4.2.7 on 2023-11-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_catagory_product_sub_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.catagory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_catagory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.sub_catagory'),
        ),
    ]
