# Generated by Django 4.2.7 on 2023-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in stock', 'IN STOCK'), ('out of stock', 'OUT OF STOCK')], max_length=200, null=True),
        ),
    ]
